# Generated by Django 2.0.4 on 2018-04-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('time', models.TimeField(verbose_name='event time')),
                ('eating_club', models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CO', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CA', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='description')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('time', models.TimeField(verbose_name='event time')),
                ('eating_club', models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CO', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CA', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('netid', models.CharField(max_length=10)),
                ('res_college', models.CharField(choices=[('NN', 'None'), ('MA', 'Mathey'), ('RO', 'Rocky'), ('BU', 'Butler'), ('WI', 'Wilson'), ('WH', 'Whitman'), ('FO', 'Forbes')], default='NN', max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('eating_club', models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CO', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CA', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2)),
                ('clubs_bickering', models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CO', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CA', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2)),
                ('picture', models.URLField(verbose_name='profile picture')),
            ],
        ),
        migrations.AddField(
            model_name='personalevent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.User'),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.User'),
        ),
    ]
