# Generated by Django 2.0.3 on 2018-04-09 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20180409_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 14, 20, 14, 649276)),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 14, 20, 14, 649239)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 14, 20, 14, 648466)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 14, 20, 14, 648438)),
        ),
    ]
