# Generated by Django 2.0.3 on 2018-04-12 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20180409_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 27, 50, 526311)),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 27, 50, 526283)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 27, 50, 525434)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 27, 50, 525401)),
        ),
        migrations.AddField(
            model_name='joinedevents',
            name='ClubEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.ClubEvent'),
        ),
        migrations.AddField(
            model_name='joinedevents',
            name='PersonalEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.PersonalEvent'),
        ),
        migrations.AddField(
            model_name='joinedevents',
            name='particpant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.User'),
        ),
    ]
