# Generated by Django 2.0.3 on 2018-04-14 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180412_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='eating_club',
            field=models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 20, 26, 45, 308555)),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 20, 26, 45, 308533)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='eating_club',
            field=models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 20, 26, 45, 307731)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 20, 26, 45, 307705)),
        ),
        migrations.AlterField(
            model_name='user',
            name='clubs_bickering',
            field=models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='eating_club',
            field=models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2),
        ),
    ]
