# Generated by Django 2.0.3 on 2018-04-14 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180413_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 13, 20, 38, 18, 722100)),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 13, 20, 38, 18, 722100)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='end_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 13, 20, 38, 18, 721183)),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 13, 20, 38, 18, 721183)),
        ),
        migrations.AddField(
            model_name='joinedevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PersonalEvent'),
        ),
        migrations.AddField(
            model_name='joinedevents',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
