# Generated by Django 2.0.3 on 2018-04-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180413_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='personalevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='personalevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='clubevent',
            name='end',
            field=models.CharField(default='hh:mm', max_length=5),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='start',
            field=models.CharField(default='hh:mm', max_length=5),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='end',
            field=models.CharField(default='hh:mm', max_length=5),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='start',
            field=models.CharField(default='hh:mm', max_length=5),
        ),
    ]
