# Generated by Django 2.0.3 on 2018-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180413_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
