# Generated by Django 2.0.3 on 2018-04-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180413_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(default='placeholder', verbose_name='profile picture'),
        ),
    ]
