# Generated by Django 2.0.3 on 2018-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_donotmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clubs_bickering',
            field=models.CharField(blank=True, choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eating_club',
            field=models.CharField(blank=True, choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='netid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='res_college',
            field=models.CharField(blank=True, choices=[('NN', 'None'), ('MA', 'Mathey'), ('RO', 'Rocky'), ('BU', 'Butler'), ('WI', 'Wilson'), ('WH', 'Whitman'), ('FO', 'Forbes')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
