# Generated by Django 2.0.3 on 2018-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180430_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
