# Generated by Django 2.0.3 on 2018-05-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180430_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=40)),
                ('start', models.CharField(default='hh:mm', max_length=5)),
                ('end', models.CharField(default='hh:mm', max_length=5)),
                ('eating_club', models.CharField(choices=[('NN', 'None'), ('IV', 'The Ivy Club'), ('CT', 'University Cottage Club'), ('TI', 'Tiger Inn'), ('CA', 'Cap and Gown Club'), ('CO', 'Colonial Club'), ('CN', 'Cannon Club'), ('CH', 'Princeton Charter Club'), ('QU', 'Quadrangle Club'), ('TO', ' Princeton Tower Club'), ('TE', 'Terrace Club'), ('CL', 'Cloister Inn')], default='NN', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='PastJoinedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PastEvent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
