from django.db import models

# Create your models here.
class User(models.Model):
	# id primary key generated by model
	first_name = models.CharField(max_length=40)
	last_name = models.CharField(max_length=40)
	# res_college
	NONE = 'NN'
	MATHEY = 'MA'
	ROCKY = 'RO'
	BUTLER = 'BU'
	WILSON = 'WI'
	WHITMAN = 'WH'
	FORBES = 'FO'
	RES_COLLEGE_CHOICES = (
		(NONE = 'None'),
		(MATHEY, 'Mathey'),
		(ROCKY, 'Rocky'),
		(BUTLER, 'Butler'),
		(WILSON, 'Wilson'),
		(WHITMAN, 'Whitman'),
		(FORBES, 'Forbes'),
	)
	res_college = models.CharField(
		max_length=2,
		choices = RES_COLLEGE_CHOICES,
		default = NONE,
	)
	year = models.CharField(max_length=4)
	eating_club
	clubs_bickering
	picture
	user_permission

class PersonalEvent(models.Model):
	event_type
	date_posted
	author = models.ForeignKey
	description
	title
	location
	time
	eating_club
	tags

class ClubEvent(models.Model):
	event_type
	data_posted
	author
	description
	title
	location
	time
	eating_club
	tags
